[package]
name = "hangry-games"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
witty-phrase-generator = "0.3.0"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
