[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
fake = "3.0.1"
rand = { version = "0.8.5" }
rstest = "0.24.0"
serde = { version = "1.0.216", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
witty-phrase-generator = "0.3.0"

[dependencies.getrandom]
#features = ["wasm_js"]
version = "0.2.15"
features = ["js"]
