[package]
name = "game"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fake = "3.0.1"
indefinite = "0.1.9"
rand = { version = "0.8.5", features = ["small_rng"] }
rstest = "0.24.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.27.0", features = ["derive"] }
strum_macros = "0.27.0"
tracing = "0.1.41"
witty-phrase-generator = "0.3.0"
uuid = { version = "1.13.2", features = ["v4", "js"] }
chrono = { version = "0.4.40", features = ["serde"] }
once_cell = "1.21.1"

[dependencies.getrandom]
version = "0.2.15"
features = ["js"]
