[package]
name = "announcers"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-stream = "0.3.6"
futures = "0.3.31"
ollama-rs = { version = "0.3.0", features = ["stream"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["macros"] }
tokio-stream = "0.1.17"
