[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
dotenvy = "0.15.7"
game = { path = "../game" }
serde = { version = "1.0.217", features = ["derive"] }
shared = { path = "../shared" }
surrealdb = "2.1.4"
surrealdb-migrations = "2.1.0"
thiserror = "2.0.8"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
tower = { version = "0.5.2", features = ["util", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde_json = "1.0.135"

[target.'cfg(windows)'.dependencies]
surrealdb = { version = "2.1.4", features = ["kv-mem"] }

[target.'cfg(unix)'.dependencies]
surrealdb = { version = "2.1.4", features = ["kv-rocksdb"] }
