[package]
name = "api"
version = "0.1.13"
edition = "2024"

[dependencies]
announcers = { path = "../announcers" }
axum = { version = "0.8.4", features = ["macros"] }
futures = "0.3.31"
game = { path = "../game" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shared = { path = "../shared" }
strum = { version = "0.27.1", features = ["derive"] }
surrealdb = "2.3.2"
surrealdb-migrations = "2.2.2"
thiserror = "2.0.12"
tokio = { version = "1.45.0", features = ["full"] }
tower-http = { version = "0.6.4", features = ["trace", "cors"] }
tower = { version = "0.5.2", features = ["util", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
uuid = { version = "1.16.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
surrealdb = { version = "2.2.1", features = ["kv-mem"] }

[target.'cfg(unix)'.dependencies]
surrealdb = { version = "2.2.1", features = ["kv-surrealkv"] }
