[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
dotenvy = "0.15.7"
game = { path = "../game" }
mockall = "0.13.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
shared = { path = "../shared" }
strum = { version = "0.27.1", features = ["derive"] }
strum_macros = "0.27.1"
surrealdb = "2.1.4"
surrealdb-migrations = "2.1.0"
thiserror = "2.0.8"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
tower = { version = "0.5.2", features = ["util", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
uuid = { version = "1.13.2", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
surrealdb = { version = "2.1.4", features = ["kv-mem"] }

[target.'cfg(unix)'.dependencies]
surrealdb = { version = "2.1.4", features = ["kv-rocksdb"] }

[dependencies.getrandom]
version = "0.2.15"
