use dotenvy::dotenv_override;
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    generate_env_file();
    generate_icons_module();

    println!("cargo:rerun-if-changed=assets/icons");
    println!("cargo:rerun-if-changed=.env");
}

fn generate_env_file() {
    let dest_path = "./src/env.rs";
    let mut f = File::create(dest_path).unwrap();

    dotenv_override().ok();
    f.write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap();

    for (key, value) in env::vars() {
        if key.starts_with("APP_") {
            let line = format!(
                "pub const {}: &str = \"{}\";\n",
                key,
                value.replace("\"", "\\\"")
            );
            f.write_all(line.as_bytes()).unwrap();
        }
    }
}

fn generate_icons_module() {
    let base = std::env::current_dir().expect("CARGO build cwd");
    let icons_root = base.join("assets/icons");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = std::path::PathBuf::from(out_dir).join("icons_generated.rs");

    let mut entries: Vec<IconEntry> = Vec::new();
    collect_tier(&icons_root.join("ui"), "Ui", "0 0 24 24", &mut entries);
    collect_tier(
        &icons_root.join("narrative"),
        "Narrative",
        "0 0 512 512",
        &mut entries,
    );

    entries.sort_by(|a, b| a.variant.cmp(&b.variant));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit by hand.\n");
    out.push_str("// Edit SVGs in web/assets/icons/{ui,narrative}/ and rebuild.\n\n");

    out.push_str("use dioxus::prelude::*;\n");
    out.push_str("use crate::components::ui::{Icon, IconSize, IconTier};\n\n");

    // Inline sprite string.
    out.push_str("pub const SPRITE: &str = \"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" style=\\\"display:none\\\">");
    for e in &entries {
        out.push_str(&format!(
            "<symbol id=\\\"{}\\\" viewBox=\\\"{}\\\">{}</symbol>",
            escape_for_rust_str(&e.sprite_id),
            escape_for_rust_str(&e.view_box),
            escape_for_rust_str(&e.body),
        ));
    }
    out.push_str("</svg>\";\n\n");

    // IconName enum.
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum IconName {\n");
    for e in &entries {
        out.push_str(&format!("    {},\n", e.variant));
    }
    out.push_str("}\n\n");

    out.push_str("impl IconName {\n");
    out.push_str("    pub fn sprite_id(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for e in &entries {
        out.push_str(&format!(
            "            IconName::{} => \"{}\",\n",
            e.variant, e.sprite_id
        ));
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    pub fn view_box(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for e in &entries {
        out.push_str(&format!(
            "            IconName::{} => \"{}\",\n",
            e.variant, e.view_box
        ));
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    pub fn tier(&self) -> IconTier {\n");
    out.push_str("        match self {\n");
    for e in &entries {
        out.push_str(&format!(
            "            IconName::{} => IconTier::{},\n",
            e.variant, e.tier
        ));
    }
    out.push_str("        }\n    }\n");
    out.push_str("}\n\n");

    // Per-icon wrapper components.
    for e in &entries {
        out.push_str(&format!(
            "#[component]\npub fn {wrapper}(\n    #[props(default)] size: Option<IconSize>,\n    #[props(default)] class: String,\n    #[props(default)] aria_label: Option<String>,\n) -> Element {{\n    rsx! {{\n        Icon {{\n            sprite_id: \"{sprite_id}\".to_string(),\n            view_box: \"{view_box}\".to_string(),\n            tier: IconTier::{tier},\n            size, class, aria_label\n        }}\n    }}\n}}\n\n",
            wrapper = e.wrapper,
            sprite_id = e.sprite_id,
            view_box = e.view_box,
            tier = e.tier,
        ));
    }

    std::fs::write(&dest, out).expect("write icons_generated.rs");
}

#[allow(dead_code)]
struct IconEntry {
    name: String,
    variant: String,
    wrapper: String,
    sprite_id: String,
    view_box: String,
    tier: &'static str,
    body: String,
}

fn collect_tier(dir: &Path, tier: &'static str, view_box: &str, out: &mut Vec<IconEntry>) {
    if !dir.is_dir() {
        return;
    }
    let entries = std::fs::read_dir(dir).expect("read icons tier dir");
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("svg") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("stem")
            .to_string();
        let raw = std::fs::read_to_string(&path).expect("read svg");
        let body = extract_svg_body(&raw);
        let prefix = match tier {
            "Ui" => "ui-",
            "Narrative" => "narrative-",
            _ => unreachable!(),
        };
        let sprite_id = format!("{}{}", prefix, stem.replace('_', "-"));
        let variant = snake_to_camel(&stem);
        let wrapper = format!("{}Icon", variant);
        out.push(IconEntry {
            name: stem,
            variant,
            wrapper,
            sprite_id,
            view_box: view_box.to_string(),
            tier,
            body,
        });
    }
}

/// Take everything between the opening `<svg ...>` tag and the closing `</svg>`.
fn extract_svg_body(raw: &str) -> String {
    let after_open = match raw.find('>') {
        Some(i) => &raw[i + 1..],
        None => return String::new(),
    };
    let before_close = match after_open.rfind("</svg>") {
        Some(i) => &after_open[..i],
        None => after_open,
    };
    before_close.trim().to_string()
}

fn snake_to_camel(s: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in s.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn escape_for_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
