use dotenvy::dotenv_override;
use std::env;
use std::fs;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    // Generate environment constants
    generate_env_file();

    // Generate SVG sprite sheet from icon components
    generate_sprite_sheet();

    println!("cargo:rerun-if-changed=web/src/components/icons/");
    println!("cargo:rerun-if-changed=.env");
}

fn generate_env_file() {
    let dest_path = "./src/env.rs";
    let mut f = File::create(dest_path).unwrap();

    dotenv_override().ok();
    f.write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap();

    for (key, value) in env::vars() {
        if key.starts_with("APP_") {
            let line = format!(
                "pub const {}: &str = \"{}\";\n",
                key,
                value.replace("\"", "\\\"")
            );
            f.write_all(line.as_bytes()).unwrap();
        }
    }
}

fn generate_sprite_sheet() {
    let base_dir = std::env::current_dir().unwrap();
    let icons_dir = base_dir.join("web/src/components/icons");
    let output_path = base_dir.join("web/assets/icons.svg");

    // Ensure output directory exists
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).ok();
    }

    let mut sprite_sheet =
        String::from(r#"<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">"#);

    // Process game icons (these are the heavy ones with ~36 icons)
    let game_icons_dir = icons_dir.join("game_icons_net");
    process_icons_dir(&game_icons_dir, &mut sprite_sheet);

    sprite_sheet.push_str("</svg>");

    let mut file = fs::File::create(output_path).expect("Failed to create sprite sheet");
    file.write_all(sprite_sheet.as_bytes())
        .expect("Failed to write sprite sheet");
}

fn process_icons_dir(dir: &Path, output: &mut String) {
    if !dir.is_dir() {
        return;
    }

    let entries = fs::read_dir(dir).expect("Failed to read icons directory");

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "rs") {
            let content = fs::read_to_string(&path).unwrap_or_default();

            // Extract icon name from filename (e.g., "dead.rs" -> "dead")
            let name = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("unknown");

            // Skip mod.rs files
            if name == "mod" {
                continue;
            }

            // Extract the SVG path data
            if let Some((view_box, path_data)) = extract_svg_data(&content) {
                let symbol = format!(
                    r#"<symbol id="icon-{}" viewBox="{}"><path d="{}"/></symbol>"#,
                    name, view_box, path_data
                );
                output.push_str(&symbol);
            }
        }
    }
}

fn extract_svg_data(content: &str) -> Option<(String, String)> {
    // Find viewBox and path d attributes
    let mut view_box = "0 0 512 512".to_string();
    let mut path_d = String::new();

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("view_box:") {
            // Extract viewBox value
            if let Some(start) = trimmed.find('"')
                && let Some(end) = trimmed[start + 1..].find('"')
            {
                view_box = trimmed[start + 1..start + 1 + end].to_string();
            }
        }

        if trimmed.starts_with("d:") || trimmed.starts_with("d:\"") {
            // Extract path d value
            let d_start = if trimmed.starts_with("d:\"") {
                trimmed.find("d:\"").map(|p| p + 3)
            } else {
                trimmed.find("d:").map(|p| p + 2)
            };

            if let Some(start) = d_start {
                let after_d = &trimmed[start..];
                if let Some(quote_start) = after_d.find('"')
                    && let Some(quote_end) = after_d[quote_start + 1..].find('"')
                {
                    path_d = after_d[quote_start + 1..quote_start + 1 + quote_end].to_string();
                }
            }
        }
    }

    if path_d.is_empty() {
        None
    } else {
        Some((view_box, path_d))
    }
}
