[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6.1", features = ["web", "router"] }
dioxus-logger = "0.6.1"
dioxus-query = "0.6.0"
dotenvy = "0.15.7"
game = { path = "../game" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde-wasm-bindgen = "0.6.5"
surrealdb = "2.1.4"
num-traits = "0.2.19"

[dependencies.getrandom]
version = "0.2.15"
features = ["js"]

[features]
default = ["web"]
web = ["dioxus/web"]
