[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6.3", features = ["web", "router"] }
dioxus-logger = "0.6.2"
dioxus-query = "0.6.0"
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
game = { path = "../game" }
gloo-storage = "0.3.0"
serde = { version = "1.0.216", features = ["derive"] }
shared = { path = "../shared" }
reqwest = { version = "0.12.9", features = ["json"] }

[dependencies.getrandom]
version = "0.2.15"
features = ["js"]

[dependencies.wasm-bindgen]
version = "0.2.99"

[features]
default = ["web"]
web = ["dioxus/web"]
